"""PPP/PPPB electron-collision operator in optical-coherence space.

This module implements the impact-limit operator specified by Appendix B of
Calisti et al., *The PPP Code -- User Manual* (2024), HAL hal-04501367v1.
The working coherence basis is ordered as ``|upper_i><lower_j|`` with the
flattened index ``i * n_lower + j``.
"""

from functools import lru_cache
import warnings

import numpy as np
from scipy.linalg import eig, solve

from starkzee.radiator import angular_dipole_element, build_basis


def _shell_rephasing(n):
    """Return the ``(-1)^l`` basis phase used by the production Stark matrix."""
    return np.array([(-1.0) ** state.l for state in build_basis(n)])


def rephase_transition_dipoles(dipoles, n_u, n_l):
    """Express signed radiative dipoles in the production Stark basis.

    The analytic intra-shell Stark matrix uses a positive radial convention,
    related to the signed hydrogenic radial functions by ``|nlm> ->
    (-1)^l |nlm>``. Intensities are insensitive to this phase, but the complex
    PPP interference residues are not.
    """
    phase_u = _shell_rephasing(n_u)
    phase_l = _shell_rephasing(n_l)
    return {
        q: phase_l[:, np.newaxis] * np.asarray(matrix) * phase_u[np.newaxis, :]
        for q, matrix in dipoles.items()
    }


@lru_cache(maxsize=None)
def intrashell_cartesian_dipoles(n, Z):
    """Return signed ``(x, y, z)`` dipole matrices within shell ``n`` [a0].

    These matrices use the same rephased, positive intra-shell radial
    convention as :func:`starkzee.static_profile.build_stark_matrix`.
    """
    basis = build_basis(n)
    dim = len(basis)
    spherical = {q: np.zeros((dim, dim), dtype=complex) for q in (-1, 0, 1)}
    for row, bra in enumerate(basis):
        for col, ket in enumerate(basis):
            if bra.ms != ket.ms or abs(bra.l - ket.l) != 1:
                continue
            l_high = max(bra.l, ket.l)
            radial = (3.0 * n / (2.0 * Z)) * np.sqrt(n**2 - l_high**2)
            for q in (-1, 0, 1):
                angular = angular_dipole_element(
                    bra.l, bra.ml, ket.l, ket.ml, q)
                spherical[q][row, col] = -radial * angular

    x = (spherical[-1] + spherical[1]) / np.sqrt(2.0)
    y = 1j * (spherical[-1] - spherical[1]) / np.sqrt(2.0)
    z = spherical[0]
    cartesian = tuple((matrix + matrix.conj().T) / 2.0 for matrix in (x, y, z))
    for matrix in cartesian:
        if not np.allclose(matrix, matrix.conj().T, rtol=0, atol=1e-13):
            raise RuntimeError("Internal shell dipole matrix is not Hermitian.")
    return cartesian


@lru_cache(maxsize=None)
def _intrashell_r2(n, Z):
    """Return the cached within-shell sum of squared Cartesian dipoles."""
    matrices = intrashell_cartesian_dipoles(n, Z)
    return sum((matrix @ matrix for matrix in matrices),
               np.zeros_like(matrices[0]))


def build_ppp_collision_operator(
    eigenvectors_u,
    eigenvectors_l,
    n_u,
    n_l,
    Z,
    impact_coefficient,
    *,
    electron_interference=True,
):
    """Build the impact-limit PPP electron operator ``Phi`` [eV].

    ``impact_coefficient`` is the common positive coefficient [eV/a0²]
    multiplying all three terms of Appendix B Eq. (B1), evaluated directly
    from the manual's impact-limit ``G(0)``. The upper and lower self terms are
    generated by their own selected-shell dipole sums. A common coefficient is
    required for the operator to retain the positive
    ``sum_c (R_u,c - R_l,c)^2`` structure.
    """
    vectors_u = np.asarray(eigenvectors_u, dtype=complex)
    vectors_l = np.asarray(eigenvectors_l, dtype=complex)
    dim_u = vectors_u.shape[0]
    dim_l = vectors_l.shape[0]
    if vectors_u.shape != (dim_u, dim_u) or vectors_l.shape != (dim_l, dim_l):
        raise ValueError("Upper and lower eigenvector arrays must be square.")
    if dim_u != 2 * n_u**2 or dim_l != 2 * n_l**2:
        raise ValueError("Eigenvector dimensions do not match the requested shells.")
    if impact_coefficient < 0:
        raise ValueError("Impact coefficient must be nonnegative.")

    r_u = tuple(vectors_u.conj().T @ r @ vectors_u
                for r in intrashell_cartesian_dipoles(n_u, Z))
    r_l = tuple(vectors_l.conj().T @ r @ vectors_l
                for r in intrashell_cartesian_dipoles(n_l, Z))
    # Rotate the already-summed r^2 operators once. This is identical to
    # summing (V† r_c V)^2 for unitary V, but avoids six repeated products at
    # every microfield quadrature point.
    a_u = vectors_u.conj().T @ _intrashell_r2(n_u, Z) @ vectors_u
    a_l = vectors_l.conj().T @ _intrashell_r2(n_l, Z) @ vectors_l
    scale = float(impact_coefficient)

    # Appendix B Eq. (B1), with flattened ordering (upper, lower). The first
    # two terms are the upper/lower self contributions. The third term is the
    # negative upper-lower interference contribution and couples transitions.
    phi = scale * (np.kron(a_u, np.eye(dim_l))
                   + np.kron(np.eye(dim_u), a_l.T))
    if electron_interference and scale:
        # Form all three Cartesian Kronecker products in one contraction. For
        # the 400-dimensional D-gamma coherence space this avoids several
        # large temporary matrices and is markedly faster than summing kron.
        cross = np.einsum(
            'cik,cjl->ijkl',
            np.asarray(r_u),
            np.asarray([lower.T for lower in r_l]),
            optimize=True,
        ).reshape(phi.shape)
        phi -= 2.0 * scale * cross

    # Roundoff can leave an O(eps) anti-Hermitian part although Eq. (B1) is
    # Hermitian in the impact limit.
    phi = (phi + phi.conj().T) / 2.0
    return phi


def ppp_complex_sdts(
    transition_energies,
    eigenvectors_u,
    eigenvectors_l,
    dipoles,
    n_u,
    n_l,
    Z,
    impact_coefficient,
    natural_widths,
    *,
    electron_interference=True,
):
    """Diagonalize ``L_f - i Phi`` and return complex PPP SDTs.

    Returns ``(omega, gamma, strengths)``. ``strengths[q]`` is the manual's
    generalized intensity ``a_k + i c_k``. The corresponding static profile is

    ``sum((a*gamma + c*(E-omega)) / ((E-omega)**2 + gamma**2)) / pi``.
    """
    energies = np.asarray(transition_energies, dtype=float)
    vectors_u = np.asarray(eigenvectors_u, dtype=complex)
    vectors_l = np.asarray(eigenvectors_l, dtype=complex)
    dim_l, dim_u = energies.shape
    if vectors_u.shape != (dim_u, dim_u) or vectors_l.shape != (dim_l, dim_l):
        raise ValueError("Transition-energy and eigenvector dimensions disagree.")
    natural = np.asarray(natural_widths, dtype=float)
    if natural.ndim == 0:
        natural = np.full_like(energies, float(natural))
    if natural.shape != energies.shape or np.any(natural < 0):
        raise ValueError("natural_widths must be nonnegative and match transition energies.")

    phi = build_ppp_collision_operator(
        vectors_u, vectors_l, n_u, n_l, Z, impact_coefficient,
        electron_interference=electron_interference,
    )
    phi = phi + np.diag(natural.T.ravel())
    generator = np.diag(energies.T.ravel()) - 1j * phi
    eigenvalues, right = eig(generator, check_finite=True)

    widths = -eigenvalues.imag
    tolerance = 1e-10 * max(1.0, float(np.max(np.abs(eigenvalues.real))))
    if np.min(widths) < -tolerance:
        raise ValueError(
            "PPP collision operator produced growing modes; the selected finite "
            "closure is not dissipative for these settings."
        )
    widths = np.maximum(widths, 0.0)

    rephased = rephase_transition_dipoles(dipoles, n_u, n_l)
    q_order = tuple(rephased)
    vectors = []
    for q in q_order:
        uncoupled = rephased[q]
        dressed = vectors_l.conj().T @ uncoupled @ vectors_u
        # Appendix B uses d_{alpha,beta}=<upper alpha|d|lower beta>,
        # the Hermitian-conjugate orientation of the stored lower-by-upper
        # emission matrix.
        vectors.append(dressed.conj().T.ravel())

    # Only R^{-1}d_q is required for the residues. Solving the three dipole
    # right-hand sides together avoids forming the complete inverse of the
    # dense eigenvector matrix. scipy.linalg.solve also performs its own
    # reciprocal-condition check and warns for an ill-conditioned system.
    dipole_vectors = np.column_stack(vectors)
    coordinates = solve(
        right, dipole_vectors, assume_a='gen', check_finite=False)
    projections = dipole_vectors.conj().T @ right
    residues = (projections * coordinates.T).conj()

    residual = np.linalg.norm(right @ coordinates - dipole_vectors)
    residual /= max(np.linalg.norm(dipole_vectors), np.finfo(float).tiny)
    if residual > 1e-8:
        warnings.warn(
            f"PPP collision eigenvector solve has relative residual "
            f"{residual:.3e}; complex SDT residues may be inaccurate.",
            RuntimeWarning,
            stacklevel=2,
        )

    order = np.argsort(eigenvalues.real)
    return eigenvalues.real[order], widths[order], {
        q: residues[index, order] for index, q in enumerate(q_order)
    }


def generalized_lorentzian(energies, frequencies, widths, strengths):
    """Evaluate the PPP generalized-Lorentzian sum as a density per eV."""
    energy = np.asarray(energies, dtype=float)
    frequency = np.asarray(frequencies, dtype=float)
    gamma = np.asarray(widths, dtype=float)
    strength = np.asarray(strengths, dtype=complex)
    delta = energy[:, np.newaxis] - frequency[np.newaxis, :]
    denominator = delta**2 + gamma[np.newaxis, :] ** 2
    numerator = (strength.real[np.newaxis, :] * gamma[np.newaxis, :]
                 + strength.imag[np.newaxis, :] * delta)
    return np.sum(numerator / denominator, axis=1) / np.pi


def generalized_lorentzian_components(
        energies, frequencies, widths, strengths_by_q):
    """Evaluate several polarizations using one shared pole kernel.

    The frequencies and widths of the non-Hermitian modes are common to every
    polarization. Building their energy denominator once is considerably
    cheaper than three independent :func:`generalized_lorentzian` calls.

    Returns a dictionary with the same keys as ``strengths_by_q``.
    """
    energy = np.asarray(energies, dtype=float)
    frequency = np.asarray(frequencies, dtype=float)
    gamma = np.asarray(widths, dtype=float)
    q_order = tuple(strengths_by_q)
    strengths = np.vstack([
        np.asarray(strengths_by_q[q], dtype=complex) for q in q_order
    ])
    delta = energy[:, np.newaxis] - frequency[np.newaxis, :]
    denominator = delta**2 + gamma[np.newaxis, :] ** 2
    absorption = gamma[np.newaxis, :] / denominator
    dispersion = delta / denominator
    profiles = (absorption @ strengths.real.T
                + dispersion @ strengths.imag.T) / np.pi
    return {q: profiles[:, index] for index, q in enumerate(q_order)}
